#!/bin/bash

# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# run plain WO to make sure that the enclave is registered 
./test-work-order.py --input_file work_orders/wo_test_input_plain.json --output_file work_orders/wo_output.json


# create encrypted input JSON using correct enclave RSA encryption key
python encrypt_wo_data.py encrypt -a work_orders/aes_keys.json -r work_orders/data/rsa_pub_key.pem -i work_orders/wo_test_input_plain.json -o work_orders/wo_test_input_enc.json

# execute the WO with encrypted data
./test-work-order.py --input_file work_orders/wo_test_input_enc.json --output_file work_orders/wo_output.json

# decrept JSOn putput (create JSON file with decrypted data)
python encrypt_wo_data.py decrypt -a work_orders/aes_keys.json -i work_orders/wo_output.json -o work_orders/wo_test_output_dec.json

# If everything worked as expected, wo_test_output_dec.json should contain JSON result with decrypted data 
